export const WORKSPACE_NAV_ITEMS = [
  'Dashboard',
  'Guide',
  'Trading',
  'Events',
  'Deliveries',
  'Scheduling',
  'Risk',
  'Positions',
  'Operations',
  'Settlement',
  'Reports',
  'Reference Data',
  'Admin',
  'Settings',
  'Assistant',
] as const
