import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it } from 'vitest'

import { DocumentIngestionPageEditor } from '../src/features/documents/DocumentIngestionPageEditor'
import type { DocumentIngestionController } from '../src/features/documents/useDocumentIngestionController'
import type { DocumentIngestionPageRecord, DocumentIngestionRecord, DocumentKindSchemaRecord } from '../src/shared/models'

function buildController(overrides: Partial<DocumentIngestionController> = {}): DocumentIngestionController {
  return {
    documents: [],
    processorSettings: null,
    reprocessProviderByDocument: {},
    systemAiConfidenceThresholdPercent: 46,
    aiConfidenceThresholdOverridePercent: null,
    effectiveAiConfidenceThresholdPercent: 46,
    schemaRegistry: null,
    schemaByKind: {},
    loading: false,
    loadError: '',
    uploading: false,
    uploadError: '',
    gmailImporting: false,
    gmailImportError: '',
    gmailImportSummary: '',
    gmailMessageQuery: '',
    gmailMessages: [],
    gmailMessagesLoading: false,
    gmailMessagesError: '',
    gmailNextPageToken: null,
    selectedGmailMessageId: null,
    selectedGmailMessage: null,
    selectedGmailMessageLoading: false,
    selectedGmailMessageError: '',
    displayName: '',
    selectedProcessorProvider: 'builtin',
    selectedProcessorModel: '',
    selectedFile: null,
    isDragActive: false,
    lastUploadedDocumentId: null,
    lastImportedDocumentIds: [],
    expandedDocumentIds: {},
    savingTarget: null,
    saveErrors: {},
    pagePreviewUrls: {},
    pagePreviewLoading: {},
    pagePreviewErrors: {},
    fileInputRef: { current: null },
    setDisplayName: () => undefined,
    setSelectedProcessorProvider: () => undefined,
    setSelectedProcessorModel: () => undefined,
    setAiConfidenceThresholdOverridePercent: () => undefined,
    setDocumentReprocessProvider: () => undefined,
    toggleDocumentExpanded: () => undefined,
    updateSelectedFile: () => undefined,
    openFilePicker: () => undefined,
    handleDropzoneKeyDown: () => undefined,
    handleDropzoneDragEnter: () => undefined,
    handleDropzoneDragOver: () => undefined,
    handleDropzoneDragLeave: () => undefined,
    handleDropzoneDrop: () => undefined,
    handleSubmit: async () => undefined,
    handleImportGmailInbox: async () => undefined,
    setGmailMessageQuery: () => undefined,
    handleRefreshGmailMessages: async () => undefined,
    handleLoadMoreGmailMessages: async () => undefined,
    handleSelectGmailMessage: async () => undefined,
    updateDocumentDraft: () => undefined,
    updatePageDraft: () => undefined,
    handleSaveDocument: async () => undefined,
    handleVerifyDocument: async () => undefined,
    handleSetDocumentKind: async () => undefined,
    handleSavePage: async () => undefined,
    handleReprocessDocument: async () => undefined,
    handleExecuteActionPlan: async () => undefined,
    setSchemaFieldValue: () => undefined,
    addCustomField: () => undefined,
    updateCustomField: () => undefined,
    removeField: () => undefined,
    addTableBlock: () => undefined,
    removeTableBlock: () => undefined,
    setTableTemplate: () => undefined,
    updateTableTitle: () => undefined,
    addTableColumn: () => undefined,
    renameTableColumn: () => undefined,
    removeTableColumn: () => undefined,
    addTableRow: () => undefined,
    removeTableRow: () => undefined,
    updateTableCell: () => undefined,
    ...overrides,
  }
}

function buildPage(overrides: Partial<DocumentIngestionPageRecord> = {}): DocumentIngestionPageRecord {
  return {
    page_id: 1,
    page_number: 1,
    classification_status: 'ANALYZED',
    extraction_status: 'ANALYZED',
    document_kind: 'INVOICE',
    document_subtype: null,
    classification_confidence: 0.94,
    classification_payload: {
      system_document_kind: 'INVOICE',
      system_document_subtype: null,
      system_classification_source: 'heuristic',
      system_classification_confidence: 0.94,
      system_matched_by: 'text:invoice',
      classification_corrected: false,
      learning_applied: false,
      learning_example_count: 0,
    },
    header_fields: [],
    table_blocks: [],
    raw_text_excerpt: 'Invoice Number INV-9001 Total Amount USD 79250',
    text_source: 'pdf_text',
    preview_available: false,
    processing_warnings: [],
    processing_errors: [],
    review_status: 'UNREVIEWED',
    review_notes: null,
    reviewed_at: null,
    reviewed_by: null,
    processed_at: '2026-05-16T12:00:00Z',
    processor_trace: null,
    routing_assessment: null,
    understanding: {
      bundle_version: 'document-understanding-v1',
      text_stats: {
        source: 'pdf_text',
        text_available: true,
        character_count: 48,
        line_count: 2,
        token_count: 8,
        numeric_token_count: 3,
        date_like_value_count: 0,
        currency_marker_count: 1,
      },
      layout_hints: {
        non_empty_line_count: 2,
        short_line_count: 2,
        uppercase_line_count: 0,
        key_value_line_count: 2,
        table_like_line_count: 0,
      },
      structure_signals: {
        header_candidate_count: 3,
        header_candidate_keys: ['invoice_number', 'invoice_date', 'total_amount'],
        table_candidate_count: 0,
        table_template_keys: [],
        table_column_count: 0,
        table_column_keys: [],
        table_row_count: 0,
      },
      visual_signals: {
        preview_generated: false,
        preview_available: false,
        image_has_visible_content: false,
        ocr_used: false,
      },
      content_fingerprint: {
        filename_signature: 'invoice packet',
        content_features: ['invoice', 'number', 'amount_due'],
        content_feature_count: 3,
        learning_version: 'content-similarity-v1',
      },
      classification_evidence: {
        system_document_kind: 'INVOICE',
        system_document_subtype: null,
        system_classification_source: 'heuristic',
        system_classification_confidence: 0.94,
        matched_by: 'text:invoice',
        corrected: false,
        correction_count: 0,
        corrected_document_kind: null,
        corrected_document_subtype: null,
        learning_applied: false,
        learning_source: null,
        learning_similarity: null,
        learning_example_count: 0,
        automated_document_kind: null,
        automated_document_subtype: null,
      },
      deterministic_assessment: {
        assessment_version: 'deterministic-score-v1',
        document_kind: 'INVOICE',
        document_subtype: null,
        confidence: 0.94,
        matched_by: 'text:invoice;required_fields:invoice_number,invoice_date,total_amount',
        supporting_evidence: [
          'Detected invoice terminology in extracted text (invoice).',
          'Matched required invoice fields: Invoice Number, Invoice Date, Total Amount.',
        ],
        conflicts: ['Parsed table content did not cleanly match the expected line items layout.'],
      },
    },
    ...overrides,
  }
}

function buildDocument(page: DocumentIngestionPageRecord): DocumentIngestionRecord {
  return {
    document_id: 'DOC-9001',
    original_filename: 'invoice-packet.pdf',
    display_name: 'Invoice Packet',
    content_type: 'application/pdf',
    storage_key: 'documents/DOC-9001.pdf',
    sha256: '0'.repeat(64),
    size_bytes: 4096,
    page_count: 1,
    source_available: true,
    status: 'ANALYZED',
    processor_provider: 'builtin',
    processor_model: null,
    classifier_version: 'deterministic-v1',
    extractor_version: 'extractor-v1',
    analysis_summary: {
      dominant_document_kind: 'INVOICE',
      reviewed_page_count: 0,
      review_ready: false,
    },
    processing_errors: [],
    review_status: 'UNREVIEWED',
    review_notes: null,
    reviewed_at: null,
    reviewed_by: null,
    created_at: '2026-05-16T12:00:00Z',
    created_by: 'document_processor',
    updated_at: '2026-05-16T12:00:00Z',
    updated_by: 'document_processor',
    version: 1,
    processor_trace: null,
    routing_assessment: null,
    linkage_assessment: null,
    action_plan: null,
    record_links: [],
    pages: [page],
    understanding: {
      bundle_version: 'document-understanding-v1',
      page_count: 1,
      text_stats: {
        pages_with_text: 1,
        source_counts: { none: 0, pdf_text: 1, ocr: 0 },
        total_character_count: 48,
        total_line_count: 2,
        total_token_count: 8,
        total_numeric_token_count: 3,
        total_date_like_value_count: 0,
        total_currency_marker_count: 1,
      },
      structure_signals: {
        header_candidate_count: 3,
        header_candidate_keys: ['invoice_number', 'invoice_date', 'total_amount'],
        table_candidate_count: 0,
        table_template_keys: [],
        table_column_count: 0,
        table_column_keys: [],
        table_row_count: 0,
      },
      visual_signals: {
        preview_generated_page_count: 0,
        preview_available_page_count: 0,
        visible_content_page_count: 0,
      },
      content_fingerprint: {
        filename_signature: 'invoice packet',
        content_features: ['invoice', 'number', 'amount_due'],
        content_feature_count: 3,
        learning_version: 'content-similarity-v1',
      },
      deterministic_assessment: {
        assessment_version: 'deterministic-score-v1',
        document_kind: 'INVOICE',
        document_subtype: null,
        confidence: 0.94,
        matched_by: 'page_consensus:invoice',
        supporting_evidence: ['1 of 1 pages scored as Invoice deterministically.'],
        conflicts: [],
      },
    },
  }
}

function buildSchema(): DocumentKindSchemaRecord {
  return {
    document_kind: 'INVOICE',
    label: 'Invoice',
    document_family: 'SETTLEMENT',
    description: 'Commercial invoice',
    review_guidance: 'Confirm the invoice identity and amount.',
    linkage_summary: 'Link to invoice and trade records.',
    record_targets: [],
    matching_keys: ['invoice_number'],
    facets: [],
    extraction_schema_code: 'INVOICE.v1',
    deep_extraction_required: true,
    extraction_objects: [],
    validation_rules: [],
    review_rules: [],
    header_fields: [],
    table_templates: [],
  }
}

describe('DocumentIngestionPageEditor', () => {
  it('renders deterministic classification evidence and conflicts', () => {
    const page = buildPage()
    const document = buildDocument(page)

    const markup = renderToStaticMarkup(
      createElement(DocumentIngestionPageEditor, {
        controller: buildController(),
        document,
        page,
        schema: buildSchema(),
        schemaRegistry: {
          version: 'doc-schema-v1',
          document_kinds: [buildSchema()],
        },
      }),
    )

    expect(markup).toContain('DETERMINISTIC')
    expect(markup).toContain('Detected invoice terminology in extracted text (invoice).')
    expect(markup).toContain('Matched required invoice fields: Invoice Number, Invoice Date, Total Amount.')
    expect(markup).toContain('Watch for: Parsed table content did not cleanly match the expected line items layout.')
  })
})
