import assert from 'node:assert/strict'

import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { test } from 'vitest'

import type { DeliveryRecord } from '../src/shared/models'
import { DeliveryWorkspace } from '../src/workspaces/shipments/ShipmentWorkspace'

function buildDelivery(overrides: Partial<DeliveryRecord>): DeliveryRecord {
  return {
    delivery_id: 'DLV-1001',
    trade_id: 'TRD-1001',
    leg_no: null,
    external_trade_id: null,
    status: 'READY',
    direction: 'OUTBOUND',
    mode_family: 'LOGISTICS',
    transport_mode: 'RAIL',
    transport_mode_source: 'EXPLICIT',
    delivery_profile: 'LOAD_DISCHARGE_WINDOW',
    book: 'PHYS_GAS',
    book_source: 'TRADE_DERIVED',
    portfolio: 'GULF_COAST',
    portfolio_source: 'TRADE_DERIVED',
    counterparty: 'Rail Buyer',
    counterparty_source: 'TRADE_DERIVED',
    commodity_class: 'GAS',
    commodity: 'Gas',
    volume: 25000,
    unit_of_measure: 'MMBTU',
    trade_currency_code: 'USD',
    price_unit_code: 'MMBTU',
    location_code: 'WAHA',
    location_source: 'TRADE_DERIVED',
    delivery_start: '2026-05-10',
    delivery_end: '2026-05-11',
    delivery_window_source: 'TRADE_DERIVED',
    origin_location_code: 'WAHA',
    origin_location_code_source: 'TRADE_DERIVED',
    destination_location_code: 'HSC',
    destination_location_code_source: 'TRADE_DERIVED',
    carrier_name: 'BNSF',
    carrier_name_source: 'MANUAL',
    carrier_reference: null,
    carrier_reference_source: null,
    asset_reference: null,
    asset_reference_source: null,
    incoterm_code: null,
    incoterm_code_source: null,
    equipment_type: 'HOPPER',
    equipment_type_source: 'MANUAL',
    load_reference: null,
    load_reference_source: null,
    discharge_reference: null,
    discharge_reference_source: null,
    rail_route_code: 'BNSF_WAHA_TO_HSC',
    rail_route_code_source: 'MANUAL',
    rail_line_code: 'BNSF_SOUTHERN_TRANSCON',
    railroad_code: 'BNSF',
    rail_route_direction: 'FORWARD',
    rail_schedule_timezone: 'America/Chicago',
    rail_service_calendar_code: 'US_GAS_DAY',
    rail_placement_cutoff_time_local: '15:00',
    rail_release_cutoff_time_local: '11:00',
    rail_placement_free_time_hours: 48,
    rail_release_free_time_hours: 24,
    origin_station_code: null,
    origin_station_code_source: null,
    destination_station_code: null,
    destination_station_code_source: null,
    waybill_reference: null,
    waybill_reference_source: null,
    release_number: null,
    release_number_source: null,
    unit_train_id: null,
    unit_train_id_source: null,
    railcar_count: null,
    railcar_count_source: null,
    receipt_location_code: null,
    receipt_location_code_source: null,
    delivery_location_code: null,
    delivery_location_code_source: null,
    pipeline_system: null,
    pipeline_system_source: null,
    pipeline_path: null,
    pipeline_path_source: null,
    pipeline_contract_number: null,
    pipeline_contract_number_source: null,
    pipeline_cycle_code: null,
    pipeline_cycle_code_source: null,
    nomination_reference: null,
    nomination_reference_source: null,
    market_operator: null,
    market_operator_source: null,
    pricing_node_code: null,
    pricing_node_code_source: null,
    delivery_node_code: null,
    delivery_node_code_source: null,
    profile_code: null,
    profile_code_source: null,
    schedule_reference: null,
    schedule_reference_source: null,
    interval_minutes: null,
    interval_minutes_source: null,
    timezone_name: null,
    timezone_name_source: null,
    execution_status: 'SCHEDULED',
    execution_status_source: 'MANUAL',
    event_count: 1,
    latest_event_type: 'PLAN_CAPTURED',
    latest_event_at: '2026-05-09T12:00:00Z',
    operations_owner: 'Ops Rail',
    operations_owner_source: 'MANUAL',
    external_reference: null,
    external_reference_source: 'SYSTEM_GENERATED',
    ops_notes: 'Ready to move',
    ops_notes_source: 'MANUAL',
    booked_at: '2026-05-08T12:00:00Z',
    last_updated_at: '2026-05-09T12:00:00Z',
    age_days: 1,
    pricing_status: 'PRICED',
    confirmation_status: 'CONFIRMED',
    nomination_status: 'NOT_REQUIRED',
    allocation_status: 'NOT_REQUIRED',
    actualization_status: 'PENDING',
    actualized_quantity: null,
    actualized_at: null,
    actualization_source: null,
    actualization_notes: null,
    actualization_updated_at: null,
    actualization_variance_quantity: null,
    invoice_status: 'NOT_REQUIRED',
    payment_status: 'CURRENT',
    settlement_status: 'OPEN',
    blocker_count: 0,
    blockers: [],
    scheduling_stage: 'READY',
    scheduling_owner: 'Ops Rail',
    scheduling_due_at: '2026-05-10T12:00:00Z',
    open_scheduling_work_item_count: 0,
    next_scheduling_workflow_type: null,
    next_scheduling_workflow_status: null,
    scheduling_work_items: [],
    delivery_events: [],
    ...overrides,
  }
}

test('deliveries workspace applies map-sourced rail-route focus before local text filtering', () => {
  const markup = renderToStaticMarkup(
    createElement(DeliveryWorkspace, {
      authSession: null,
      routeHandoff: {
        source: 'map',
        tradeId: 'BNSF_WAHA_TO_HSC',
        focus: {
          type: 'reference_record',
          id: 'BNSF_WAHA_TO_HSC',
          label: 'BNSF Waha to Houston Ship Channel',
        },
        tradeInspectorTab: null,
        eventType: null,
        label: 'Open deliveries for BNSF_WAHA_TO_HSC',
        rationale:
          'This workspace started focused on the selected rail route so you can review the matching deliveries before widening back to the full board.',
        filter: 'BNSF_WAHA_TO_HSC',
        sourceRunId: null,
        sourceConversationId: null,
        sourceActionRequestId: null,
      },
      globalFilter: '',
      commodities: [
        {
          code: 'Gas',
          name: 'Gas',
          description: 'Test gas commodity',
          is_active: true,
          commodity_class: 'GAS',
          allowed_transport_modes: ['RAIL', 'TRUCK'],
        },
      ],
      deliveries: [
        buildDelivery({ delivery_id: 'DLV-1001', trade_id: 'TRD-1001' }),
        buildDelivery({
          delivery_id: 'DLV-2002',
          trade_id: 'TRD-2002',
          rail_route_code: 'CN_AECO_TO_DAWN',
          rail_line_code: 'CN_MAINLINE',
          railroad_code: 'CN',
          commodity: 'Gas East',
        }),
      ],
      operationalResourceDescriptors: [],
      formatCommodityClass: (value: string) => value,
      formatDate: (value: string | null | undefined) => value ?? 'n/a',
      formatDateOnly: (value: string | null | undefined) => value ?? 'n/a',
      formatNumber: (value: number | null) => (value == null ? '—' : String(value)),
      deliveryMutationError: '',
      deliveryMutationPendingId: null,
      deliverySyncError: '',
      deliverySyncSuccess: '',
      deliveriesSyncing: false,
      onOpenTrade: () => undefined,
      onClearHandoff: () => undefined,
      onSyncDeliveriesFromTrades: async () => undefined,
      onSaveDelivery: async () => undefined,
      onSaveDeliveryLogisticsDetails: async () => undefined,
      onSaveDeliveryPipelineDetails: async () => undefined,
      onSaveDeliveryPowerDetails: async () => undefined,
      onCreateDeliveryEvent: async () => undefined,
    }),
  )

  assert.match(markup, /Open deliveries for BNSF_WAHA_TO_HSC/)
  assert.match(markup, /1 of 2 deliveries match/)
  assert.match(markup, /Rail route BNSF_WAHA_TO_HSC is currently in focus/)
  assert.match(markup, /TRD-1001/)
  assert.doesNotMatch(markup, /DLV-2002/)
  assert.doesNotMatch(markup, /TRD-2002/)
  assert.match(markup, /Show Full Board/)
})
