from __future__ import annotations

from fastapi import Query

STANDARD_LIST_LIMIT_DEFAULT = 50
STANDARD_LIST_LIMIT_MAX = 500
ADMIN_LIST_LIMIT_DEFAULT = 100
ADMIN_LIST_LIMIT_MAX = 1000
LIST_OFFSET_DEFAULT = 0

STANDARD_LIST_LIMIT_QUERY = Query(default=STANDARD_LIST_LIMIT_DEFAULT, ge=1, le=STANDARD_LIST_LIMIT_MAX)
ADMIN_LIST_LIMIT_QUERY = Query(default=ADMIN_LIST_LIMIT_DEFAULT, ge=1, le=ADMIN_LIST_LIMIT_MAX)
LIST_OFFSET_QUERY = Query(default=LIST_OFFSET_DEFAULT, ge=0)
