export type RecordedRequest = {
  method: string
  path: string
  search: string
}

export const smokeAccessToken = 'smoke-access-token'

export const smokeSession = {
  sessionId: 'smoke-session-1',
  accessToken: smokeAccessToken,
  expiresAt: '2099-01-01T00:00:00Z',
  user: {
    user_id: 'ops_admin',
    email: 'ops@example.com',
    display_name: 'Ops Admin',
    role: 'OPS_ADMIN',
  },
} as const

export const publicRuntimeSettings = {
  app_version: 'smoke-build',
  database: {
    dialect: 'sqlite',
    name: 'smoke.db',
    size_bytes: 1024,
    table_count: 12,
    record_count: 42,
  },
  cors_allow_origins: ['http://127.0.0.1'],
  mutation_protection_enabled: true,
  bootstrap_admin_enabled: false,
  single_user_auth_enabled: false,
  google_auth: {
    enabled: false,
    client_id: null,
    auto_create_users: false,
  },
  session_ttl_hours: 24,
  eia_base_url: 'https://api.eia.gov',
  eia_timeout_seconds: 30,
  assistant: {
    enabled: false,
    default_provider: 'openai',
    effective_default_provider: null,
    configured_provider_count: 0,
    providers: [],
    available_tools: [],
    available_action_types: [],
  },
  pagination: {
    standard_default: 100,
    standard_max: 500,
    admin_default: 100,
    admin_max: 500,
  },
} as const

export const assistantRuntimeSettings = {
  enabled: true,
  default_provider: 'openai',
  effective_default_provider: 'openai',
  configured_provider_count: 1,
  providers: [
    {
      provider: 'openai',
      label: 'OpenAI',
      enabled: true,
      configured: true,
      is_default: true,
      default_model: 'gpt-5.4',
      base_url: 'https://api.openai.com/v1',
      setup_env_var: 'OPENAI_API_KEY',
    },
  ],
  available_tools: [
    {
      name: 'get_trade_by_id',
      description: 'Load one live trade projection by exact trade_id.',
    },
  ],
  available_action_types: [
    {
      name: 'cancel_trade',
      label: 'Cancel trade',
      description: 'Cancel a trade through the approval queue when the live trade evidence supports it.',
    },
  ],
} as const

export const tradeAttentionCandidates = [
  {
    trade_id: 'T-AMEND-100',
    candidate_types: ['confirmation_backlog'],
    source_count_keys: ['dashboard.attention.confirmation_backlog_count'],
    priority_reason: 'Older unconfirmed trades rise first in the confirmation queue.',
    trade_nature: 'PHYSICAL',
    book: 'GULF_GAS',
    portfolio: 'GULF_PROMPT',
    counterparty: 'ALPHA_MKT',
    commodity_class: 'NATURAL_GAS',
    commodity: 'HENRY_HUB_GAS',
    trader_user: 'trader.alpha',
    trade_date: '2026-04-10',
    execution_timestamp: '2026-04-10T16:00:00Z',
    delivery_start: '2026-04-12',
    delivery_end: '2026-04-12',
    confirmation_status: 'PENDING',
    nomination_status: 'PENDING',
    allocation_status: 'PENDING',
    pricing_status: 'PENDING',
    invoice_status: 'PENDING',
    payment_status: 'PENDING',
    settlement_status: 'PENDING',
    age_days: 3,
    supporting_records: {
      current_confirmation_id: 41,
    },
    suggested_next_tool: 'get_trade_confirmation_by_id',
    next_steps: ['Review the confirmation blocker with the operations owner.'],
    blocking_reasons: ['Counterparty acknowledgement is still missing.'],
    recommended_action: {
      action_type: 'issue_trade_confirmation',
      requires_approval: true,
      payload: {
        trade_id: 'T-AMEND-100',
        confirmation_id: 41,
      },
    },
  },
  {
    trade_id: 'T-AMEND-100',
    candidate_types: ['payment_due', 'overdue_payment'],
    source_count_keys: [
      'settlement.payment_due_count',
      'dashboard.attention.overdue_payment_count',
    ],
    priority_reason: 'Overdue cash rises ahead of merely due payments.',
    trade_nature: 'PHYSICAL',
    book: 'GULF_GAS',
    portfolio: 'GULF_PROMPT',
    counterparty: 'ALPHA_MKT',
    commodity_class: 'NATURAL_GAS',
    commodity: 'HENRY_HUB_GAS',
    trader_user: 'trader.alpha',
    trade_date: '2026-04-10',
    execution_timestamp: '2026-04-10T16:00:00Z',
    delivery_start: '2026-04-12',
    delivery_end: '2026-04-12',
    confirmation_status: 'CONFIRMED',
    nomination_status: 'COMPLETED',
    allocation_status: 'COMPLETED',
    pricing_status: 'PRICED',
    invoice_status: 'ISSUED',
    payment_status: 'OVERDUE',
    settlement_status: 'INVOICED',
    age_days: 3,
    supporting_records: {
      candidate_invoice_id: 501,
      candidate_invoice_number: 'INV-501',
    },
    suggested_next_tool: 'get_trade_payment_by_id',
    next_steps: ['Collect overdue cash against invoice INV-501.'],
    blocking_reasons: ['Cash collection is past the scheduled due date.'],
    recommended_action: {
      action_type: 'create_trade_payment',
      requires_approval: true,
      payload: {
        trade_id: 'T-AMEND-100',
        invoice_id: 501,
      },
    },
  },
  {
    trade_id: 'T-AMEND-100',
    candidate_types: ['stale_pricing'],
    source_count_keys: ['dashboard.attention.stale_pricing_count'],
    priority_reason: 'Older unresolved pricing work rises first.',
    trade_nature: 'PHYSICAL',
    book: 'GULF_GAS',
    portfolio: 'GULF_PROMPT',
    counterparty: 'ALPHA_MKT',
    commodity_class: 'NATURAL_GAS',
    commodity: 'HENRY_HUB_GAS',
    trader_user: 'trader.alpha',
    trade_date: '2026-04-10',
    execution_timestamp: '2026-04-10T16:00:00Z',
    delivery_start: '2026-04-12',
    delivery_end: '2026-04-12',
    confirmation_status: 'CONFIRMED',
    nomination_status: 'COMPLETED',
    allocation_status: 'COMPLETED',
    pricing_status: 'PENDING',
    invoice_status: 'PENDING',
    payment_status: 'PENDING',
    settlement_status: 'PENDING',
    age_days: 3,
    supporting_records: {},
    suggested_next_tool: 'get_trade_by_id',
    next_steps: ['Finish pricing follow-through in Trade Capture.'],
    blocking_reasons: [],
    recommended_action: null,
  },
] as const

export const invoiceIssueCandidates = [
  {
    trade_id: 'T-AMEND-100',
    trade_nature: 'PHYSICAL',
    book: 'GULF_GAS',
    portfolio: 'GULF_PROMPT',
    counterparty: 'ALPHA_MKT',
    commodity_class: 'NATURAL_GAS',
    commodity: 'HENRY_HUB_GAS',
    trader_user: 'trader.alpha',
    trade_date: '2026-04-10',
    execution_timestamp: '2026-04-10T16:00:00Z',
    delivery_start: '2026-04-12',
    delivery_end: '2026-04-12',
    trade_currency_code: 'USD',
    invoice_status: 'PENDING',
    payment_status: 'PENDING',
    settlement_status: 'PENDING',
    notional_amount: 78750,
    age_days: 3,
    readiness_status: 'READY',
    priority_reason: 'Ready-to-issue invoice candidates rise before blocked previews.',
    preview_summary: 'Ready to issue the first invoice from settlement.',
    blocking_reasons: [],
    assumptions: ['Delivery quantities have been finalized for invoicing.'],
    recommended_action: {
      action_type: 'issue_trade_invoice',
      requires_approval: true,
      payload: {
        trade_id: 'T-AMEND-100',
      },
      preview_status: 'READY',
    },
  },
] as const

const smokeTokenBudget = {
  status: 'GREEN',
  allocated_tokens: 50000,
  used_tokens: 4200,
  remaining_tokens: 45800,
  percent_used: 0.084,
  warning_threshold_percent: 0.75,
  allocation_source: 'AGENT',
  window_started_at: '2026-04-11T00:00:00Z',
  reset_at: '2026-04-12T00:00:00Z',
} as const

const smokeAllowedToolDecision = {
  resource_type: 'tool',
  resource_id: 'get_trade_by_id',
  policy_key: 'assistant.tool.get_trade_by_id.smoke.v1',
  allowed: true,
  reason: 'Allowed by the smoke role-derived profile.',
  risk_level: 'LOW',
  approval_required: false,
  max_scope: 'TEAM',
  roles: ['OPS_ADMIN'],
  workspaces: ['assistant', 'admin', 'trades'],
} as const

const smokeAllowedActionDecision = {
  resource_type: 'action',
  resource_id: 'cancel_trade',
  policy_key: 'assistant.action.cancel_trade.smoke.v1',
  allowed: true,
  reason: 'Allowed for approval-gated smoke governance review.',
  risk_level: 'HIGH',
  approval_required: true,
  max_scope: 'TEAM',
  roles: ['OPS_ADMIN'],
  workspaces: ['assistant', 'admin', 'trades'],
} as const

export const assistantAdminAgents = [
  {
    agent_id: 'ops-governor',
    name: 'Ops Governor',
    description: 'Proposes high-impact trade actions that require admin review.',
    status: 'ACTIVE',
    scope: 'TEAM',
    provider: 'openai',
    model: 'gpt-5.4',
    role_key: 'trade-ops-copilot',
    profile_kind: 'ROLE_DERIVED',
    specialization_summary: 'Smoke profile for trade operations governance coverage.',
    human_owner_role: 'Operations Lead',
    authority_ceiling: 'STAGE',
    activation_notes: 'Smoke fixture mirrors a role-derived active pilot profile.',
    profile_request_id: null,
    allowed_workspaces: ['assistant', 'admin', 'trades'],
    capabilities: ['READ', 'ACTION'],
    allowed_tools: ['get_trade_by_id'],
    allowed_action_types: ['cancel_trade'],
    daily_token_allocation: 50000,
    token_budget: smokeTokenBudget,
    effective_policy: {
      allowed_tools: [smokeAllowedToolDecision],
      blocked_tools: [],
      allowed_actions: [smokeAllowedActionDecision],
      blocked_actions: [],
      policy_notes: ['Smoke fixture policy validated for the active role-derived profile.'],
    },
    eval_gate: {
      status: 'PASS',
      role_key: 'trade-ops-copilot',
      required_cases: ['Allowed action staging.', 'Denied overreach.'],
      covered_cases: ['Allowed action staging.', 'Denied overreach.'],
      missing_cases: [],
      custom_case_count: 2,
      notes: ['Smoke fixture marks the active role profile as covered.'],
    },
    system_prompt: 'Escalate cross-user trade actions into an approval inbox before execution.',
    created_at: '2026-04-11T08:00:00Z',
    created_by: 'ops_admin',
    updated_at: '2026-04-11T08:30:00Z',
    updated_by: 'ops_admin',
    version: 3,
  },
  {
    agent_id: 'pre-trade-structuring-agent',
    name: 'Pre-Trade Structuring Agent',
    description: 'Converts market context and internal constraints into review-ready trade ideas.',
    status: 'DRAFT',
    scope: 'TEAM',
    provider: null,
    model: null,
    role_key: 'pre-trade-structuring-agent',
    profile_kind: 'ROLE_DERIVED',
    specialization_summary: 'Phase 1 pilot draft for pre-trade structuring.',
    human_owner_role: 'Trader',
    authority_ceiling: 'DRAFT',
    activation_notes: 'Phase 1 pilot draft. Requires outcome review before activation.',
    profile_request_id: null,
    allowed_workspaces: ['assistant', 'trades', 'risk', 'positions', 'reports', 'reference'],
    capabilities: ['READ', 'EXPLAIN', 'DRAFT'],
    allowed_tools: ['get_market_context'],
    allowed_action_types: [],
    daily_token_allocation: 25000,
    token_budget: {
      ...smokeTokenBudget,
      allocated_tokens: 25000,
      used_tokens: 0,
      remaining_tokens: 25000,
      percent_used: 0,
    },
    effective_policy: {
      allowed_tools: [],
      blocked_tools: [],
      allowed_actions: [],
      blocked_actions: [],
      policy_notes: ['Draft-only Phase 1 profile; no action authority granted.'],
    },
    eval_gate: {
      status: 'NOT_REQUIRED',
      role_key: 'pre-trade-structuring-agent',
      required_cases: [],
      covered_cases: [],
      missing_cases: [],
      custom_case_count: 0,
      notes: ['Draft-only profile does not require activation evals yet.'],
    },
    system_prompt: 'Draft review-ready trade structures with assumptions and human review needs separated.',
    created_at: '2026-04-11T08:05:00Z',
    created_by: 'ops_admin',
    updated_at: '2026-04-11T08:05:00Z',
    updated_by: 'ops_admin',
    version: 1,
  },
] as const

export const assistantRoleArchetypes = [
  {
    role_key: 'trade-ops-copilot',
    name: 'Trade Ops Copilot',
    description: 'Coordinates trade operations follow-through with staged, reviewable actions.',
    catalog_status: 'SEEDED',
    mission: ['Keep booked trades moving.', 'Stage the smallest justified action.'],
    human_owner_role: 'Operations Lead',
    allowed_workspaces: ['assistant', 'trades', 'operations'],
    work_objects: ['trade', 'workflow item'],
    capability_ceiling: ['READ', 'EXPLAIN', 'DRAFT', 'ACTION'],
    default_tools: ['get_trade_by_id'],
    maximum_action_types: ['cancel_trade', 'update_trade_workflow_item'],
    authority_ceiling: 'STAGE',
    approval_rules: ['Operations Lead reviews staged actions before execution.'],
    stop_conditions: ['Evidence is ambiguous.', 'Requested action exceeds the role boundary.'],
    success_metrics: ['High approval rate.', 'Low stale action rate.'],
    required_eval_coverage: ['Allowed action staging.', 'Denied overreach.'],
    base_prompt_guidance: ['Lead with the blocker.', 'Show evidence before staging.'],
    current_profile_ids: ['trade-ops-copilot'],
  },
  {
    role_key: 'pre-trade-structuring-agent',
    name: 'Pre-Trade Structuring Agent',
    description: 'Converts market context and internal constraints into review-ready trade ideas.',
    catalog_status: 'PHASE_1',
    mission: ['Convert researched opportunities into reviewable trade structures and assumptions.'],
    human_owner_role: 'Trader',
    allowed_workspaces: ['assistant', 'trades', 'risk', 'positions', 'reports', 'reference'],
    work_objects: ['pre-trade scenario', 'pre-trade review item', 'trade intent'],
    capability_ceiling: ['READ', 'EXPLAIN', 'DRAFT'],
    default_tools: ['get_market_context', 'search_reference_data', 'list_positions'],
    maximum_action_types: [],
    authority_ceiling: 'DRAFT',
    approval_rules: ['Trader owns review decisions and any trade capture.'],
    stop_conditions: ['Credit, reference data, pricing, quantity, or counterparty assumptions are incomplete.'],
    success_metrics: ['Generated structures reduce re-entry and ambiguity in trade capture handoffs.'],
    required_eval_coverage: ['Review-ready scenario draft.', 'Denied direct trade booking.'],
    eval_gate: {
      status: 'NOT_REQUIRED',
      role_key: 'pre-trade-structuring-agent',
      required_cases: [],
      covered_cases: [],
      missing_cases: [],
      custom_case_count: 0,
      notes: ['Draft-only profile does not require activation evals yet.'],
    },
    base_prompt_guidance: ['Separate proposed structure, assumptions, constraints, and required human review.'],
    current_profile_ids: [],
  },
] as const

export const assistantActionRequests = [
  {
    action_request_id: 7001,
    run_id: 701,
    user_id: 'trader.alpha',
    status: 'PENDING',
    workspace: 'trades',
    agent_id: 'ops-governor',
    agent_name: 'Ops Governor',
    action_type: 'cancel_trade',
    summary: 'Cancel trade T-AMEND-100',
    description:
      'Cancel trade T-AMEND-100 because the counterparty requested a same-day unwind before confirmation.',
    payload: {
      trade_id: 'T-AMEND-100',
      reason: 'Counterparty unwind requested before confirmation.',
    },
    review_context: {
      owning_work_object: {
        type: 'trade',
        id: 'T-AMEND-100',
        label: 'Trade T-AMEND-100',
      },
      required_reviewer_role: 'OPS_ADMIN',
      business_rationale:
        'The counterparty requested a same-day unwind before confirmation, so the trade cancellation needs reviewer confirmation before any typed mutation runs.',
      proposed_mutation: {
        operation: 'cancel_trade',
        trade_id: 'T-AMEND-100',
        target_status: 'CANCELLED',
      },
      supporting_records: [
        {
          type: 'trade',
          id: 'T-AMEND-100',
          label: 'Trade T-AMEND-100',
          summary: 'ACTIVE physical trade awaiting confirmation.',
        },
        {
          type: 'workflow_item',
          id: 'OPS-CONF-100',
          label: 'Confirmation blocker',
          summary: 'Counterparty unwind note is recorded against the open confirmation item.',
        },
      ],
      assumptions: ['The unwind request applies to the latest confirmed economics for T-AMEND-100.'],
      missing_evidence: ['Signed unwind confirmation has not been uploaded yet.'],
      expected_downstream_effects: [
        'Trade status will move to CANCELLED.',
        'The open confirmation blocker will no longer need follow-through.',
      ],
      stale_state_basis: {
        trade_status: 'ACTIVE',
        confirmation_status: 'PENDING',
        last_event_id: 'evt-trade-amend-100',
      },
      idempotency_key: 'assistant-action:cancel_trade:T-AMEND-100:counterparty-unwind',
      action_preview: {
        preview_type: 'cancel_trade',
        status: 'READY',
        summary: 'Approval will cancel trade T-AMEND-100 and close the confirmation blocker.',
        affected_records: [
          {
            type: 'trade',
            id: 'T-AMEND-100',
            label: 'Trade T-AMEND-100',
            summary: 'ACTIVE trade record.',
          },
        ],
        field_changes: [
          {
            field: 'status',
            current_value: 'ACTIVE',
            proposed_value: 'CANCELLED',
          },
          {
            field: 'confirmation_status',
            current_value: 'PENDING',
            proposed_value: 'NOT_REQUIRED',
          },
        ],
        expected_side_effects: [
          'Record a TradeCancelled event.',
          'Clear the pending confirmation blocker.',
        ],
        warnings: ['Signed unwind confirmation still needs to be attached to the record.'],
        blocking_reasons: [],
        assumptions: ['No downstream invoice has been issued for this trade.'],
      },
    },
    lifecycle: {
      stage: 'AWAITING_REVIEW',
      label: 'Awaiting review',
      tone: 'attention',
      is_terminal: false,
      can_approve: true,
      can_reject: true,
      reviewer_action_label: 'Approve or reject',
      decided_label: null,
      review_risk_flags: [],
    },
    result: null,
    error_detail: null,
    review_outcome: null,
    decision_note: null,
    correction_summary: null,
    correction_fields: [],
    created_at: '2026-04-11T08:45:00Z',
    decided_at: null,
    decided_by: null,
  },
] as const

export const assistantOutcomeMetrics = {
  generated_at: '2026-04-11T09:10:00Z',
  created_after: null,
  created_before: null,
  thresholds: {
    min_decided_actions_for_promotion: 10,
    max_rejection_rate_for_promotion: 0.1,
    max_failed_execution_rate_for_promotion: 0.02,
    max_stale_action_rate_for_promotion: 0.05,
    max_correction_rate_for_promotion: 0.1,
    max_pending_actions_for_promotion: 0,
    min_decided_actions_for_pause_signal: 5,
    rejection_rate_pause_threshold: 0.4,
    failed_execution_rate_pause_threshold: 0.1,
    stale_action_rate_pause_threshold: 0.25,
    oldest_pending_hours_pause_threshold: 72,
    repeated_failed_actions_pause_threshold: 3,
    unsupported_attempt_pause_threshold: 1,
    policy_drift_pause_threshold: 1,
  },
  total_feedback_count: 2,
  helpful_feedback_count: 1,
  needs_work_feedback_count: 1,
  feedback_helpful_rate: 0.5,
  by_agent: [
    {
      agent_id: 'ops-governor',
      agent_name: 'Ops Governor',
      agent_role_key: 'trade-ops-copilot',
      agent_profile_kind: 'ROLE_DERIVED',
      run_count: 12,
      completed_run_count: 11,
      failed_run_count: 1,
      warning_count: 1,
      warning_rate: 0.0833,
      tool_call_count: 15,
      tool_error_count: 1,
      tool_error_rate: 0.0667,
      helpful_feedback_count: 8,
      needs_work_feedback_count: 1,
      feedback_helpful_rate: 0.8889,
      staged_action_count: 12,
      pending_action_count: 1,
      executed_action_count: 10,
      rejected_action_count: 1,
      failed_action_count: 0,
      correction_count: 1,
      decided_action_count: 11,
      stale_action_count: 0,
      unsupported_attempt_count: 0,
      policy_drift_count: 0,
      approval_rate: 0.9091,
      rejection_rate: 0.0909,
      failed_execution_rate: 0,
      stale_action_rate: 0,
      avg_decision_seconds: 420,
      oldest_pending_age_seconds: 1500,
      recommendation: {
        recommended_action: 'KEEP_STAGED',
        promotion_candidate: false,
        pause_recommended: false,
        reasons: ['Pending actions remain open before promotion.'],
      },
    },
  ],
  by_role: [
    {
      agent_role_key: 'trade-ops-copilot',
      run_count: 12,
      completed_run_count: 11,
      failed_run_count: 1,
      warning_count: 1,
      warning_rate: 0.0833,
      tool_call_count: 15,
      tool_error_count: 1,
      tool_error_rate: 0.0667,
      staged_action_count: 12,
      pending_action_count: 1,
      executed_action_count: 10,
      rejected_action_count: 1,
      failed_action_count: 0,
      decided_action_count: 11,
      stale_action_count: 0,
      unsupported_attempt_count: 0,
      policy_drift_count: 0,
      approval_rate: 0.9091,
      rejection_rate: 0.0909,
      failed_execution_rate: 0,
      stale_action_rate: 0,
      avg_decision_seconds: 420,
      oldest_pending_age_seconds: 1500,
      recommendation: {
        recommended_action: 'KEEP_STAGED',
        promotion_candidate: false,
        pause_recommended: false,
        reasons: ['Pending actions remain open before promotion.'],
      },
    },
  ],
  by_profile: [
    {
      agent_profile_kind: 'ROLE_DERIVED',
      run_count: 12,
      completed_run_count: 11,
      failed_run_count: 1,
      warning_count: 1,
      warning_rate: 0.0833,
      tool_call_count: 15,
      tool_error_count: 1,
      tool_error_rate: 0.0667,
      staged_action_count: 12,
      pending_action_count: 1,
      executed_action_count: 10,
      rejected_action_count: 1,
      failed_action_count: 0,
      decided_action_count: 11,
      stale_action_count: 0,
      unsupported_attempt_count: 0,
      policy_drift_count: 0,
      approval_rate: 0.9091,
      rejection_rate: 0.0909,
      failed_execution_rate: 0,
      correction_rate: 0.0909,
      stale_action_rate: 0,
      avg_decision_seconds: 420,
      oldest_pending_age_seconds: 1500,
      recommendation: {
        recommended_action: 'KEEP_STAGED',
        promotion_candidate: false,
        pause_recommended: false,
        reasons: ['Pending actions remain open before promotion.'],
      },
    },
  ],
  by_workspace: [
    {
      workspace: 'trades',
      run_count: 8,
      helpful_feedback_count: 1,
      needs_work_feedback_count: 0,
      feedback_count: 1,
      feedback_helpful_rate: 1,
    },
    {
      workspace: 'assistant',
      run_count: 4,
      helpful_feedback_count: 0,
      needs_work_feedback_count: 1,
      feedback_count: 1,
      feedback_helpful_rate: 0,
    },
  ],
  by_action_type: [
    {
      action_type: 'cancel_trade',
      staged_action_count: 12,
      pending_action_count: 1,
      executed_action_count: 10,
      rejected_action_count: 1,
      failed_action_count: 0,
      correction_count: 1,
      decided_action_count: 11,
      stale_action_count: 0,
      unsupported_attempt_count: 0,
      policy_drift_count: 0,
      approval_rate: 0.9091,
      rejection_rate: 0.0909,
      failed_execution_rate: 0,
      correction_rate: 0.0909,
      stale_action_rate: 0,
      avg_decision_seconds: 420,
      oldest_pending_age_seconds: 1500,
      recommendation: {
        recommended_action: 'KEEP_STAGED',
        promotion_candidate: false,
        pause_recommended: false,
        reasons: ['One pending cancel_trade action is still waiting for review.'],
      },
    },
  ],
  recent_feedback: [
    {
      feedback_id: 901,
      run_id: 701,
      conversation_id: 601,
      agent_id: 'ops-governor',
      agent_name: 'Ops Governor',
      workspace: 'assistant',
      user_id: 'trader.alpha',
      user_role: 'TRADER',
      rating: 'NEEDS_WORK',
      comment: 'Show the cancellation policy evidence before staging.',
      created_at: '2026-04-11T09:00:00Z',
      updated_at: '2026-04-11T09:00:00Z',
    },
    {
      feedback_id: 900,
      run_id: 700,
      conversation_id: 600,
      agent_id: 'ops-governor',
      agent_name: 'Ops Governor',
      workspace: 'trades',
      user_id: 'trader.alpha',
      user_role: 'TRADER',
      rating: 'HELPFUL',
      comment: 'Clear and actionable.',
      created_at: '2026-04-11T08:30:00Z',
      updated_at: '2026-04-11T08:30:00Z',
    },
  ],
  prompt_navigation_summary: {
    total_outcome_count: 0,
    accepted_count: 0,
    dismissed_count: 0,
    failed_count: 0,
    acceptance_rate: null,
    dismiss_rate: null,
    failure_rate: null,
  },
  by_prompt_target: [],
  recent_prompt_navigation_outcomes: [],
} as const

export const assistantPromptRouteRecommendations = [
  {
    target_view: 'operations',
    target_label: 'Open confirmation',
    target_rationale: 'Review the confirmation blocker with the operations owner.',
    focus_type: 'trade',
    accepted_count: 4,
    outcome_count: 5,
    acceptance_rate: 0.8,
    signal: 'CANDIDATE_FOR_RULE',
    signal_reasons: ['Repeated accepted handoffs make this destination a strong deterministic rule candidate.'],
  },
] as const

export const codexTaskSettings = {
  enabled: true,
  configured: false,
  provider: 'github_actions',
  repository: null,
  workflow_id: null,
  default_ref: 'main',
  prompt_input_name: 'prompt',
  missing_configuration: ['CODEX_TASK_REPOSITORY', 'CODEX_TASK_WORKFLOW_ID'],
} as const

export const codexTasks = [] as const

export const userAccounts = [
  {
    user_id: 'ops_admin',
    email: 'ops@example.com',
    display_name: 'Ops Admin',
    role: 'OPS_ADMIN',
    is_active: true,
    password_set: true,
    last_login_at: '2026-04-11T07:55:00Z',
    created_at: '2026-01-03T10:00:00Z',
    created_by: 'system',
    updated_at: '2026-04-11T07:55:00Z',
    updated_by: 'ops_admin',
    version: 4,
  },
  {
    user_id: 'trader.alpha',
    email: 'trader.alpha@example.com',
    display_name: 'Trader Alpha',
    role: 'TRADER',
    is_active: true,
    password_set: true,
    last_login_at: '2026-04-11T08:20:00Z',
    created_at: '2026-01-10T09:30:00Z',
    created_by: 'ops_admin',
    updated_at: '2026-04-11T08:20:00Z',
    updated_by: 'ops_admin',
    version: 2,
  },
] as const

export const adminRoadmapDocument = {
  document: {
    source_path: 'docs/engineering/trading-source-roadmap.md',
    horizons: [
      {
        key: 'now',
        label: 'Now',
        detail: 'Protect the highest-risk operational seams first.',
      },
      {
        key: 'next',
        label: 'Next',
        detail: 'Expand typed contracts and smoke coverage across adjacent flows.',
      },
      {
        key: 'later',
        label: 'Later',
        detail: 'Productize deeper governance and automation controls.',
      },
    ],
    phases: [
      {
        id: 'wave-0',
        title: 'Wave 0',
        priority: 'P0',
        summary: 'Protect the first operator and governance trust seams.',
        items: [
          {
            id: 'governance-smoke',
            title: 'Governance smoke coverage',
            summary: 'Protect assistant approvals with deterministic browser coverage.',
            status: 'in_progress',
            horizon: 'now',
            owner: 'Platform',
            target: 'Wave 0',
            source_ids: ['FR0-12'],
            links: [
              { label: 'Admin', view: 'admin' },
              { label: 'Assistant', view: 'assistant' },
            ],
          },
        ],
      },
    ],
    milestones: [
      {
        id: 'wave-0-trust',
        title: 'Wave 0 Trust Protected',
        summary: 'Primary workflows and one governance seam are covered by smoke automation.',
        owner: 'Platform',
        target: 'Wave 0',
        item_ids: ['governance-smoke'],
        exit_criteria: [
          'Seeded browser smoke covers one admin or assistant governance interaction.',
        ],
        links: [{ label: 'Admin', view: 'admin' }],
      },
    ],
  },
  updated_at: '2026-04-11T09:00:00Z',
  updated_by: 'ops_admin',
  version: 3,
  is_default: false,
  recent_revisions: [
    {
      revision_id: 12,
      version: 3,
      created_at: '2026-04-11T09:00:00Z',
      created_by: 'ops_admin',
      change_summary: ['Added governance smoke coverage milestone.'],
      restored_from_revision_id: null,
    },
  ],
} as const

export const projectionMonitoringAdminRecord = {
  document: {
    policy_key: 'trade-projection-monitoring',
    schedule: {
      enabled: false,
      cadence_minutes: 60,
      auto_clean_mode: 'disabled',
      max_cleanup_trades_per_run: 25,
    },
    alerting: {
      enabled: false,
      issue_count_threshold: 1,
      impacted_trade_threshold: 1,
      minimum_alert_interval_minutes: 60,
      channels: ['ADMIN_WORKSPACE'],
      routing_note: 'Seeded browser smoke monitoring policy.',
    },
  },
  updated_at: '2026-04-11T09:00:00Z',
  updated_by: 'ops_admin',
  version: 1,
  is_default: false,
  recent_revisions: [
    {
      revision_id: 31,
      version: 1,
      created_at: '2026-04-11T09:00:00Z',
      created_by: 'ops_admin',
      change_summary: ['Seeded projection monitoring smoke policy.'],
      restored_from_revision_id: null,
    },
  ],
  runtime: {
    last_evaluated_at: null,
    last_evaluated_by: null,
    last_issue_count: 0,
    last_structural_issue_count: 0,
    last_invariant_issue_count: 0,
    last_impacted_trade_count: 0,
    last_auto_cleaned_trade_count: 0,
    last_auto_cleaned_trade_ids: [],
    last_cycle_status: 'idle',
    last_alert_at: null,
    last_alert_reason: null,
    last_alert_severity: null,
  },
  recent_alerts: [],
  recent_deliveries: [],
  live_status: {
    health_status: 'disabled',
    evaluation_due: false,
    next_evaluation_at: null,
    live_issue_count: 0,
    live_structural_issue_count: 0,
    live_invariant_issue_count: 0,
    live_impacted_trade_count: 0,
    should_alert: false,
    alert_messages: [],
    last_evaluated_at: null,
    last_evaluated_by: null,
    last_alert_at: null,
    last_alert_reason: null,
  },
} as const

export const books = [
  {
    code: 'GULF_GAS',
    name: 'Gulf Gas Book',
    is_active: true,
  },
  {
    code: 'WEST_POWER',
    name: 'West Power Desk',
    is_active: true,
  },
]

export const commodities = [
  {
    code: 'HENRY_HUB_GAS',
    name: 'Henry Hub Gas',
    commodity_class: 'NATURAL_GAS',
    is_active: true,
  },
  {
    code: 'WAHA_GAS',
    name: 'Waha Gas',
    commodity_class: 'NATURAL_GAS',
    is_active: true,
  },
]

export const priceIndices = [
  {
    code: 'HH_IFERC',
    name: 'Henry Hub IFERC',
    commodity_class: 'NATURAL_GAS',
    commodity_code: 'HENRY_HUB_GAS',
    currency_code: 'USD',
    unit_code: 'MMBTU',
    provider: 'ICE',
    is_active: true,
  },
]

export const currencies = [
  {
    code: 'USD',
    name: 'US Dollar',
    symbol: '$',
    is_active: true,
  },
]

export const units = [
  {
    code: 'MMBTU',
    name: 'Million British Thermal Units',
    commodity_class: 'NATURAL_GAS',
    dimension: 'ENERGY',
    precision: 2,
    is_active: true,
  },
  {
    code: 'USD/MMBTU',
    name: 'US Dollars per MMBtu',
    commodity_class: 'NATURAL_GAS',
    dimension: 'PRICE',
    precision: 4,
    is_active: true,
  },
]

export const locations = [
  {
    code: 'HENRY_HUB',
    name: 'Henry Hub',
    location_kind: 'POINT',
    location_type: 'HUB',
    market: 'PHYSICAL',
    timezone: 'America/Chicago',
    is_active: true,
  },
  {
    code: 'WAHA_POOL',
    name: 'Waha Pool',
    location_kind: 'POINT',
    location_type: 'HUB',
    market: 'PHYSICAL',
    timezone: 'America/Chicago',
    is_active: true,
  },
]

export const assets = [
  {
    code: 'GULF_PIPELINE',
    name: 'Gulf Pipeline',
    asset_class: 'PIPELINE',
    asset_type: 'TRANSMISSION',
    asset_reality: 'REAL',
    commodity_code: 'HENRY_HUB_GAS',
    location_code: 'HENRY_HUB',
    capacity_value: 120000,
    capacity_unit_code: 'MMBTU',
    operator_name: 'Gulf Midstream',
    operating_status: 'OPERATING',
    is_active: true,
  },
]

export const assetStandards = {
  default_asset_class: 'PIPELINE',
  default_asset_type_by_class: {
    PIPELINE: 'TRANSMISSION',
  },
  asset_classes: ['PIPELINE'],
  asset_types_by_class: {
    PIPELINE: ['TRANSMISSION'],
  },
  default_asset_reality: 'REAL',
  asset_realities: ['REAL', 'SIMULATED'],
  default_operating_status: 'OPERATING',
  operating_statuses: ['OPERATING'],
} as const

export const counterparties = [
  {
    code: 'ALPHA_MKT',
    name: 'Alpha Marketing',
    counterparty_type: 'MARKETER',
    credit_status: 'APPROVED',
    is_active: true,
  },
  {
    code: 'CASCADE_UTIL',
    name: 'Cascade Utility',
    counterparty_type: 'UTILITY',
    credit_status: 'APPROVED',
    is_active: true,
  },
]

export const portfolios = [
  {
    code: 'GULF_PROMPT',
    name: 'Gulf Prompt Portfolio',
    book_code: 'GULF_GAS',
    is_active: true,
  },
  {
    code: 'WEST_BAL',
    name: 'West Balance Portfolio',
    book_code: 'WEST_POWER',
    is_active: true,
  },
]

export const positions = [
  {
    commodity: 'HENRY_HUB_GAS',
    net_volume: 25000,
    updated_at: '2026-04-10T18:30:00Z',
  },
]

export const trades = [
  {
    trade_id: 'T-AMEND-100',
    originating_option_trade_id: null,
    external_trade_id: 'ET-9001',
    source_system: 'ETRM',
    created_at: '2026-04-10T16:00:00Z',
    updated_at: '2026-04-10T16:05:00Z',
    execution_timestamp: '2026-04-10T16:00:00Z',
    trade_date: '2026-04-10',
    effective_start_date: '2026-05-01',
    effective_end_date: '2026-05-31',
    quality_spec: null,
    unit_of_measure: 'MMBTU',
    trade_currency_code: 'USD',
    location_code: 'HENRY_HUB',
    delivery_start: '2026-05-01',
    delivery_end: '2026-05-31',
    price_unit_code: 'USD/MMBTU',
    instrument_type: 'LINEAR',
    option_type: null,
    option_style: null,
    option_strike_price: null,
    option_expiration_date: null,
    trade_nature: 'PHYSICAL',
    trade_structure: 'SINGLE',
    trade_side: 'BUY',
    book: 'GULF_GAS',
    portfolio: 'GULF_PROMPT',
    counterparty: 'ALPHA_MKT',
    commodity_class: 'NATURAL_GAS',
    commodity: 'HENRY_HUB_GAS',
    pricing_type: 'FIXED',
    pricing_status: 'PENDING',
    confirmation_status: 'SENT',
    nomination_status: 'PENDING',
    allocation_status: 'PENDING',
    actualization_status: 'PENDING',
    price_index_code: null,
    price: 3.15,
    volume: 25000,
    invoice_status: 'PENDING',
    payment_status: 'PENDING',
    settlement_status: 'PENDING',
    trader_user: 'trader.alpha',
    status: 'ACTIVE',
    last_event_id: 'evt-trade-amended-100',
    active_credit_exception: null,
    credit_approval_status: 'APPROVED',
    credit_hold_active: false,
    credit_hold_reason: null,
  },
]

export const selectedTradeEvents = [
  {
    event_id: 'evt-trade-amended-100',
    aggregate_type: 'trade',
    aggregate_id: 'T-AMEND-100',
    event_type: 'TradeAmended',
    occurred_at: '2026-04-10T18:30:00Z',
    recorded_at: '2026-04-10T18:30:00Z',
    actor_id: 'ops_admin',
    correlation_id: 'corr-trade-amended-100',
    causation_id: 'evt-trade-created-100',
    schema_version: 2,
    payload: {
      confirmation_status: 'SENT',
      nomination_status: 'PENDING',
      trader_user: 'ops_admin',
    },
  },
  {
    event_id: 'evt-trade-invoice-updated-100',
    aggregate_type: 'trade',
    aggregate_id: 'T-AMEND-100',
    event_type: 'TradeInvoiceUpdated',
    occurred_at: '2026-04-10T17:45:00Z',
    recorded_at: '2026-04-10T17:45:00Z',
    actor_id: 'settlement_admin',
    correlation_id: 'corr-trade-invoice-updated-100',
    causation_id: 'evt-trade-created-100',
    schema_version: 1,
    payload: {
      invoice_status: 'ISSUED',
      payment_status: 'PENDING',
      settlement_status: 'PENDING',
    },
  },
  {
    event_id: 'evt-trade-created-100',
    aggregate_type: 'trade',
    aggregate_id: 'T-AMEND-100',
    event_type: 'TradeCreated',
    occurred_at: '2026-04-10T16:00:00Z',
    recorded_at: '2026-04-10T16:00:00Z',
    actor_id: 'ops_admin',
    correlation_id: null,
    causation_id: null,
    schema_version: 1,
    payload: {
      trade_id: 'T-AMEND-100',
      book: 'GULF_GAS',
      portfolio: 'GULF_PROMPT',
      counterparty: 'ALPHA_MKT',
      commodity_class: 'NATURAL_GAS',
      commodity: 'HENRY_HUB_GAS',
      pricing_type: 'FIXED',
      price: 3.15,
      volume: 25000,
    },
  },
]

function buildTradeWorkspaceSummary(tradeRows = trades) {
  const activeTrades = tradeRows.filter((trade) => trade.status === 'ACTIVE')

  return {
    total_count: tradeRows.length,
    active_count: activeTrades.length,
    priced_active_count: activeTrades.filter((trade) => trade.price !== null).length,
    pending_pricing_count: activeTrades.filter((trade) => trade.pricing_status === 'PENDING').length,
    pending_settlement_count: activeTrades.filter((trade) => trade.settlement_status !== 'SETTLED').length,
    tracked_book_count: new Set(activeTrades.map((trade) => trade.book)).size,
    total_active_volume: activeTrades.reduce((sum, trade) => sum + (trade.volume ?? 0), 0),
  }
}

export function buildWorkspaceSummary(tradeRows = trades) {
  const tradeSummary = buildTradeWorkspaceSummary(tradeRows)
  const confirmationBacklogCount = tradeAttentionCandidates.filter((candidate) =>
    candidate.candidate_types.includes('confirmation_backlog'),
  ).length
  const overduePaymentCount = tradeAttentionCandidates.filter((candidate) =>
    candidate.candidate_types.includes('overdue_payment'),
  ).length
  const stalePricingCount = tradeAttentionCandidates.filter((candidate) =>
    candidate.candidate_types.includes('stale_pricing'),
  ).length
  const paymentDueCount = tradeAttentionCandidates.filter((candidate) =>
    candidate.candidate_types.includes('payment_due'),
  ).length
  const invoicePendingCount = invoiceIssueCandidates.length

  return {
    generated_at: '2026-04-11T00:00:00Z',
    trades: tradeSummary,
    positions: { total_count: 1 },
    option_exposures: { total_count: 0 },
    deliveries: { total_count: 0 },
    confirmations: { total_count: 0 },
    work_items: {
      total_count: 0,
      operations_queue_count: 0,
      settlement_queue_count: 0,
    },
    invoices: { total_count: 0 },
    payments: { total_count: 0 },
    dashboard: {
      positions: {
        gross_exposure: 25000,
        position_count: 1,
        bucket_count: 1,
        buckets: [
          {
            commodity_class: 'NATURAL_GAS',
            unit_label: 'MMBTU',
            net_volume: 25000,
            commodity_count: 1,
          },
        ],
        largest_bucket: {
          commodity_class: 'NATURAL_GAS',
          unit_label: 'MMBTU',
          net_volume: 25000,
          commodity_count: 1,
        },
      },
      attention: {
        total_count: confirmationBacklogCount + overduePaymentCount + stalePricingCount,
        confirmation_backlog_count: confirmationBacklogCount,
        nomination_backlog_count: 0,
        allocation_backlog_count: 0,
        invoice_backlog_count: 0,
        overdue_payment_count: overduePaymentCount,
        stale_pricing_count: stalePricingCount,
        incomplete_ops_data_count: 0,
      },
    },
    settlement: {
      open_work_item_count: 0,
      invoice_pending_count: invoicePendingCount,
      payment_due_count: paymentDueCount,
      settled_count: 0,
      trade_exception_count: 0,
      workflow_exception_count: 0,
      breakdown: [],
    },
  }
}
